# Generated by Django 5.1.4 on 2025-07-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="chapter_timestamp",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
