# Generated by Django 5.1.4 on 2025-07-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_lesson_chapter_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="playlist_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="module",
            name="video_id",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
