# Generated by Django 5.1.4 on 2025-07-29 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_course_playlist_url_module_video_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="lesson_type",
            field=models.CharField(
                choices=[
                    ("video", "Video Lesson"),
                    ("notes", "Study Notes"),
                    ("quiz", "Quiz"),
                ],
                default="video",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="StudyNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("key_concepts", models.JSONField(default=list)),
                ("code_examples", models.JSONField(default=list)),
                ("summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_note",
                        to="courses.lesson",
                    ),
                ),
            ],
        ),
    ]
