# Generated by Django 5.1.4 on 2025-07-29 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_lesson_lesson_type_studynote"),
    ]

    operations = [
        migrations.AddField(
            model_name="studynote",
            name="golden_notes",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="studynote",
            name="own_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="studynote",
            name="summaries",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="studynote",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
