# Generated by Django 5.1.4 on 2025-07-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_studynote_golden_notes_studynote_own_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="generation_type",
            field=models.CharField(
                choices=[
                    ("link", "YouTube Link"),
                    ("prompt", "AI Prompt"),
                    ("topic", "Topic Only"),
                ],
                default="link",
                max_length=20,
            ),
        ),
    ]
