# Generated by Django 5.1.4 on 2025-07-29 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0006_course_generation_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuleNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("overview", models.TextField(blank=True)),
                ("key_concepts", models.JSONField(default=list)),
                ("golden_notes", models.JSONField(default=list)),
                ("summaries", models.JSONField(default=list)),
                ("own_notes", models.TextField(blank=True, default="")),
                ("additional_resources", models.JSONField(default=list)),
                ("content", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "module",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_note",
                        to="courses.module",
                    ),
                ),
            ],
        ),
    ]
